### ISSUE TITLE
Is this Repository still active?

### ISSUE THREAD

**Issue by johannesschobel** [Grimthorr/laravel-user-settings#15]
Dear @Grimthorr ,
I just wanted to know, if this repository is still actively managed. The last commit is > 6 months old..
Thanks a lot for commenting and cheers,
Johannes

**Comment by Grimthorr** [comment]
Hi @johannesschobel - thanks, I've not made any commits recently as I haven't used the package myself in a while so I guess it's considered at a "final" version. I'm more than happy to merge any PRs (sorry I've been a little neglectful recently but I'll take a look now).

**Comment by johannesschobel** [comment]
Good to hear @Grimthorr
