### ISSUE TITLE
No Json supported. Can you change to text or provide alternative?

### ISSUE THREAD

**Issue by filipveschool** [Grimthorr/laravel-user-settings#16]
Hi,

I wanted to ask if iT is possible to change THE json datatype to text or something else?

Because apparently the databases from my webhosting are mariadb and dont support JSON datatype.

I was using this LocalLy and I love this package but cant JSON for my actual website.

Wanted so to ask if TEXT would be possible?

**Comment by johannesschobel** [comment]
Hey @filipveschool ,
actually, this is NOT an issue of this package. The respective database maps the `JSON` type to a specific type available to the database. For example, mySQL (at least older versions) doesn't know `JSON` either, so it maps it to a simple `TEXT` type.

You can take a look at the respective [Grammars](https://github.com/laravel/framework/tree/5.1/src/Illuminate/Database/Schema/Grammars) for your database.

For example, you see, that `MySQL` transforms `JSON` to `TEXT`.

Can you close the issue?

**Comment by filipveschool** [comment]
@johannesschobel so if i make a column "settings" with dataype TEXT then the settings should function as it's supposed to be instead of datatype JSON.

Do I understand it correct?

**Comment by johannesschobel** [comment]
@filipveschool It should work "out of the box" when using `JSON`. Internally, the database should store the `JSON` datatype as a normal `TEXT` datatype, IF the database is not able to _understand_ JSON.

**Comment by filipveschool** [comment]
@johannesschobel That is weird then, because when I make a migration with "$table->json('settings');"

Then on my local mysql server that has JSON as datatype this works. But my webhosting has MariaDB which doesnt support JSON datatype and then he just gives an error and stops migrating.

**Comment by johannesschobel** [comment]
@filipveschool 
I run a MySQL Database and use the package as well. In my migration table it shows:

``` php
$table->json('settings');
```

However, my database (MySQL) does not _know_ the `JSON` datatype. The `Grammar` files, i linked earlier, show the mapping between the actual datatypes (which are available for the migration files) and the datatypes _known_ by the database. For example, MySQL maps `JSON` to `TEXT`, while PostgreSQL maps `JSON` to `JSON` (as it knows the `JSON` datatype).

**Comment by filipveschool** [comment]
@johannesschobel so could it be that it doesn't work because my database is MariaDB? Or does Laravel has no support for MariaDB?

**Comment by johannesschobel** [comment]
What Laravel Version do you run?
MariaDB is a fork of MySQL, therefore, the "core features of MySQL" should be available.
Could it be, that your provider runs an old version of MariaDB?

**Comment by filipveschool** [comment]
i work as well with laravel 5.2 and 5.3-dev-develop version.

This is the info for version of MariaDB of my provider.

DatabaseServer

Server: Localhost by UNIX socket
Servertype: MariaDB
Serverversion: 10.0.25-MariaDB-cll-lve - MariaDB Server
Protocolversion: 10

---

Webserver

Apache
Client-version of database: libmysql - mysqlnd 5.0.11-dev - 20120503

---

phpMyAdmin

Version-information: 4.0.10.16

**Comment by johannesschobel** [comment]
Ok, this [THREAD](https://laracasts.com/discuss/channels/eloquent/table-json-generates-an-error-when-running-migrations) describes the error pretty well.

In Laravel 5.1, the `JSON` migration datatype maps to `TEXT`. In Laravel 5.2, however, `JSON` maps to `JSON`.
I assume, you are running L5.2+ and an "older" version of MariaDB (which does not have a JSON datatype available). Then, of course, it crashes.

**Comment by filipveschool** [comment]
@johannesschobel 

so if I understand it correctly, 

I have to say instead of doing now: $table->**json**('settings'). 

I have to do now: $table->**text**('settings');

correct? And the rest of the functionality will work as before?

**Comment by johannesschobel** [comment]
yes, that would be the "bugfix" for now.
I have referenced this issue in the pull-request i made 2 weeks ago. Thereby, i changed from `STRING` to `TEXT`. In the discussion to the pull request you can see, that we then changed from `TEXT` to `JSON`.

However, in order to deal with your issue ("old DB version, new Laravel version), I think it would be good to move back to `TEXT` instead of `JSON`.

What do you think @Grimthorr ? I would make a new pull-request if you like!

Greetings

**Comment by johannesschobel** [comment]
The _official_ statement from one of the Laravel Core Dev Team to [this issue](https://github.com/laravel/framework/issues/13622) is:

```
This is a similar issue to having old MySQL versions. We made this change in 5.2. 
Either upgrade to a new version, or, just don't use the json type in migrations. 
If you really want to use that in the migration, and want the old database version, 
you could stay on Laravel 5.1 LTS.
```

Would be best to switch back to `TEXT` in my opinion!

**Comment by filipveschool** [comment]
@johannesschobel Thanks for all the help and explanation.

I made a workaround by setting the DB type in my .env file.

So I know which version I use locally and on my hosting and can automatically use the right DATATYPE.

Hopefully everything works now as it should be :)

**Comment by johannesschobel** [comment]
No worries - but that's not the way it should work ;)
I hope to change it back from `JSON` to `TEXT`.

**Comment by gpedro** [comment]
If you installed correctly, just go to edit the migration file.

```
        Schema::table('users', function(Blueprint $table)
        {
            $table->json('preferences');
            // when json type is not supported, use text type
            // $table->text('preferences');
        });
```

**Comment by Grimthorr** [comment]
Thanks for doing the research on this. I think it's best that we merge the changes to revert back to `TEXT` to be on the safe side. See comment at #17.
