### ISSUE TITLE
Class setting does not exist

### ISSUE THREAD

**Issue by ricardomartos** [Grimthorr/laravel-user-settings#29]
Hello,
 I'm using the function `setting()->get('some-option', 'some-default-string', Auth::user()->id)` 
inside a Blade `@if()` and I'm getting the error `Class setting does not exist`.
Also tried `Setting::get('some-option', 'some-default-string', Auth::user()->id)` 
         and `\Setting::get('some-option', 'some-default-string', Auth::user()->id)` 

I've been looking into the files and found that in the vendor files from this packages, the names don't follow a standard in "Upper-case/CammelCase", let me explain myself:

In the Facade, It returns `'setting'` ( also the helpers and ServiceProvider use all lowercase )

But the class is named `Setting`

Could this be the problem?

Also, on my mac, It works flawlessly, however in my Linux ( Ubuntu ) server does not.

Could anyone help me?

Thanks.

# **UPDATE**

Turns out that my test server had the `php artisan config:cache` , so I deleted the `config.php` file inside `bootstrap/cache` and It works again!

Hope this helps someone.

**Comment by techguydev** [comment]
Thanks a lot @ricardomartos !, it helped me.
