### ISSUE TITLE
ServiceProvider  not found

### ISSUE THREAD

**Issue by leo4all** [Grimthorr/laravel-user-settings#4]
[Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Grimthorr\LaravelUserSettings\ServiceProvider' not found

Note: If you receive a "class not found" error when running migrations, try running the composer dump-autoload command.

composer dump-autoload its not fixing this issue, on L5

any recommendations?

**Comment by Grimthorr** [comment]
Oops, I changed `composer.json` to use PSR-4 but forgot to rearrange the directory structure.

**Comment by Grimthorr** [comment]
This should be fixed in 2.0.1. Run a `composer update` and you should be good to go.
