### ISSUE TITLE
Setting::forget Not working 

### ISSUE THREAD

**Issue by leo4all** [Grimthorr/laravel-user-settings#5]
After using Setting::forget($key) 

Undefined offset: 1 on Setting.php line 106 

-> return array_get($this->settings[$constraint_value], $key, $default);

and setting still remain its values.

**Comment by Grimthorr** [comment]
Oops, `forget()` was un-setting the parent key from the cache instead of the key specified. This is fixed in [2.0.3](https://github.com/Grimthorr/laravel-user-settings/releases/tag/2.0.3).

**Comment by Grimthorr** [comment]
This was also broken for the Laravel 4 flavour; fixed in [1.1.1](https://github.com/Grimthorr/laravel-user-settings/releases/tag/1.1.1).
