### ISSUE TITLE
How can I retrive the authenticated user Id in the ConfigServiceProvider?

### ISSUE THREAD

**Issue by Wmas** [Grimthorr/laravel-user-settings#8]
This works also fine in the ConfigServiceProvider when I do

```
public function boot()
{
   $settings = Setting::all();  
}
```

But I need to do this:

```
public function boot()
{
   $settings = Setting::all($id);
}
```

Do you know how to get the Authenticated 'user Id' in the ConfigServiceProvider?

**Comment by Grimthorr** [comment]
You might not be able to grab the current user ID in a `boot()` function - you could try the `Auth` facade (`Auth::id()`) but this might not be loaded yet. This is entirely down to how Laravel handles Service Providers unfortunately.
